### ISSUE TITLE
CI: Run unit tests

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc-menu-generator#11]
Should those be exposed via meson?

Otherwise we could also just `make check` in the makefile.

**Comment by Consolatis** [comment]
See
- #14 

I can't make it work, see the failed runs at https://github.com/labwc/labwc-menu-generator/actions/runs/8431967865/job/23090242403?pr=14

**Comment by johanmalm** [comment]
Have turned it into a meson driven thing. It gets stuck on Void though. Giving up for tonight.

**Comment by johanmalm** [comment]
Closed by #14
