### ISSUE TITLE
Using labwc-menu-generator removes Reconfigure and Exit options

### ISSUE THREAD

**Issue by aethrvmn** [labwc/labwc-menu-generator#2]
Running the program as 

` labwc-menu-generator > ~/.config/labwc/menu.xml`

removes the ability to make new changes to labwc without restarting the system manually.

**Comment by johanmalm** [comment]
Sorry, missed this one.

It's intentionally designed that way.

`labwc-menu-generator` does the hard work of parsing system application .desktop files and categorizing them into directories.

Technically it would of course be possible to add options for prepend (before the application directories) and append items, but I highly suspect that many users will want customized setups, so I consider it much easier for users to write a simple wrapper script rather having to study/learn lots of configurations options (never mind the dev time to keep adding them :smile:).

I use a file similar to the one in the code block below and we should probably add something like it to a `contrib/` directory and document that intended approach in the `README.md`.


```bash
#!/bin/sh

printf '%b\n' '<?xml version="1.0" encoding="UTF-8"?>
<openbox_menu>
<menu id="root-menu" label="root-menu">
  <item label="Web Browser">
    <action name="Execute"><command><![CDATA[firefox labwc.github.io]]></command></action>
  </item>
  <item label="Terminal">
    <action name="Execute" command="sakura -e zsh" />
  </item>
  <item label="Tweaks">
    <action name="Execute" command="labwc-tweaks"/>
  </item>
  <separator />'

# -b|--bare option disables header and footer
labwc-menu-generator -b

printf '%b\n' '<separator />
  <item label="Reconfigure">
    <action name="Reconfigure" />
  </item>
  <item label="Exit">
    <action name="Exit" />
  </item>
</menu> <!-- root-menu -->
</openbox_menu>'
```
